export const RATE_LIMIT = 3_000
export const RATE_LIMIT_CREATE_ORDER = 5_000

export const statusCodes = {
  NORMAL: 0,
  DATABASE_ERROR: 1,
  INVALID_INPUT_DATA: 2,
  INVALID_API_TOKEN: 3,
  INVALID_ENDPOINT: 4,
  EXCEEDED: 5,
  ERROR: 6,
}
